// Regenerates content/social-posts.ts + public/social/ from the Meta Graph API.
// Usage: INSTAGRAM_TOKEN=... IG_USER_ID=... [FACEBOOK_TOKEN=... FB_PAGE_ID=...] npm run social:sync
// Without tokens it exits 0 and leaves the hand-made snapshot untouched, so `build` never breaks.
// ponytail: plain fetch + fs, no SDK; upgrade to a cron/CI job once the client hands over tokens.
import { mkdir, writeFile } from "node:fs/promises";

const { INSTAGRAM_TOKEN, IG_USER_ID, FACEBOOK_TOKEN, FB_PAGE_ID } = process.env;
if (!INSTAGRAM_TOKEN || !IG_USER_ID) {
  console.log("[social:sync] INSTAGRAM_TOKEN / IG_USER_ID not set: keeping the manual snapshot.");
  process.exit(0);
}

const g = async (path, token) => {
  const res = await fetch(`https://graph.facebook.com/v21.0/${path}${path.includes("?") ? "&" : "?"}access_token=${token}`);
  if (!res.ok) throw new Error(`Graph API ${res.status} for ${path}`);
  return res.json();
};
const firstSentence = (t = "") =>
  t.replace(/[\u{1F000}-\u{1FFFF}☀-➿​⁠️]/gu, "").trim().split(/(?<=[.!?])\s|\n/)[0].slice(0, 110);

const ig = await g(`${IG_USER_ID}/media?fields=id,caption,media_type,media_url,thumbnail_url,permalink&limit=4`, INSTAGRAM_TOKEN);
const posts = ig.data.map((m) => ({
  network: "Instagram",
  href: m.permalink,
  img: m.media_type === "VIDEO" ? m.thumbnail_url : m.media_url,
  caption: firstSentence(m.caption),
  reel: m.media_type === "VIDEO",
}));

if (FACEBOOK_TOKEN && FB_PAGE_ID) {
  const fb = await g(`${FB_PAGE_ID}/posts?fields=message,permalink_url,full_picture&limit=3`, FACEBOOK_TOKEN);
  for (const p of fb.data ?? []) {
    if (!p.full_picture) continue;
    posts.push({ network: "Facebook", href: p.permalink_url, img: p.full_picture, caption: firstSentence(p.message), reel: false });
  }
}

await mkdir("public/social", { recursive: true });
const rows = [];
for (const [i, p] of posts.entries()) {
  const file = `/social/post-${i + 1}.jpg`;
  const buf = Buffer.from(await (await fetch(p.img)).arrayBuffer());
  await writeFile(`public${file}`, buf);
  // Width/height: Graph API media has no dimensions; 1080x1350 is Instagram's feed size and only
  // seeds next/image's aspect hint (the grid crops to square anyway).
  rows.push(`  { network: "${p.network}", href: "${p.href}", src: "${file}", width: 1080, height: 1350, caption: "${p.caption.replace(/"/g, '\\"')}", reel: ${p.reel}${i === 0 ? ", feature: true" : ""} },`);
}
const date = new Intl.DateTimeFormat("es-CO", { day: "numeric", month: "long", year: "numeric" }).format(new Date());
const ts = `import { social } from "./engagement";

export type SocialPost = {
  network: "Instagram" | "Facebook";
  href: string;
  src: string;
  width: number;
  height: number;
  caption: string;
  reel: boolean;
  feature?: boolean;
};

// Generated by scripts/fetch-social.mjs on ${date} from the Meta Graph API. Do not edit by hand.
export const socialPosts: SocialPost[] = [
${rows.join("\n")}
];
void social;
`;
await writeFile("content/social-posts.ts", ts);
console.log(`[social:sync] wrote ${posts.length} posts. Update social.snapshotDate in content/engagement.ts to "${date}".`);
